### ISSUE TITLE
Configurable ssh config and known_hosts file locations

### ISSUE THREAD

**Issue by woegjiub** [Shougo/neossh.vim#11]
Would it be possible to have new settings for the config and known hosts file locations?

The config location would be "~/.ssh/config" unless changed.

The known_hosts location would be "~/.ssh/known_hosts" unless changed.

**Comment by Shougo** [comment]
Please explain the reason.

> The config location would be "~/.ssh/config" unless changed.
> The known_hosts location would be "~/.ssh/known_hosts" unless changed.

This is used for the completion.
The option is used for the completion?

**Comment by Shougo** [comment]
I can find the configuration file option in ssh command.
But I cannot find the known_hosts file option.

**Comment by woegjiub** [comment]
In autoload/unite/sources/ssh.vim, at lines 454 and 463, you open those files.

Mine are located at $XDG_CONFIG_HOME/ssh/config and $XDG_DATA_HOME/ssh/known_hosts, I do this so that i only have .cache, .config, and .local in $HOME.

These variables would mean I could change the files used at those lines without patching neossh.vim

http://linux.die.net/man/5/ssh_config

UserKnownHostsFile: Specifies a file to use for the user host key database instead of ~/.ssh/known_hosts.

**Comment by Shougo** [comment]
I think "Configurable ssh config" is OK.
But "known_hosts" is not OK.

> UserKnownHostsFile: Specifies a file to use for the user host key database instead of ~/.ssh/known_hosts. 

You should specify it in the config file.

**Comment by woegjiub** [comment]
You will use the value from the config file instead of writing `if filereadable(expand('~/.ssh/known_hosts'))` at autoload/unite/sources/ssh.vim line 463?

**Comment by Shougo** [comment]
Yes.

**Comment by woegjiub** [comment]
Thank you! That is even better!

**Comment by stfl** [comment]
What is the status on this change?

**Comment by Shougo** [comment]
No progress....
I'm very busy about other plugins(deoplete, dein.vim, unite.vim,..) and neovim/Vim patches.

The PR is wellcome.

**Comment by Shougo** [comment]
Implemented.
