### ISSUE TITLE
Incompatibilities with Windows

### ISSUE THREAD

**Issue by Pidgeot** [Shougo/neossh.vim#12]
I have been trying to get neossh (with VimFiler) to work on Windows, unsuccessfully so far.

* In unite#sources#ssh#ssh_list, single quotes are used to quote the command sent over SSH, and double quotes are used to quote the command used by sh. Windows' cmd.exe, however, does not allow single quotes to quote arguments, so it does not get interpreted correctly by the SSH client.

A simple fix for this is to simply swap the use of double and single quotes, i.e. `printf('%s "sh -c ''LC_TIME=C %s %s''"'`.

* In unite#sources#ssh#create_file_dict, the time returned in the listing is converted to a timestamp, using either the gdate or the date command. I have found two problems with this:

    * The timestamp sent to the gdate command must be double-quoted, as per the previous issue - the string function uses single-quotes.
    * `date` is a shell built-in to change the computer date - it cannot parse dates, so it must be avoided on Windows

* gVim seems to stop responding to input after the file list has loaded - console vim works fine, though.

* Attempting to open a file generates the following error message:

```
function vimfiler#handler#_event_handler..<SNR>106_on_BufReadCmd..unite#vimfiler_check_filetype..unite#start#vimfiler_check_filetype..469, line 55
Vim(bdelete):E94: No matching buffer for -1
Error occurred while executing "open" action!
```

This error does not seem to appear when opening local files via VimFiler.

**Comment by Shougo** [comment]
Unfortunatelly, I don't support Windows in neossh.
So, I cannot fix it.  But pull request is wellcome.

**Comment by Pidgeot** [comment]
I've figured out the responsiveness issue - when gVim is running, and neossh calls gdate, a command-line window gets spawned temporarily, and because vimfiler forces a refresh using an autocmd for FocusGained, gVim keeps gaining and losing focus. It isn't possible to avoid this: all console-based applications - such as gdate - will spawn a console on Windows if they don't have one available (the console used for Vim is apparently good enough here). 

I can see two ways to easily deal with this:
1) Disable date parsing entirely on Windows (at least for gVim)
2) Disable the autocmd for gVim on Windows when dealing with ssh listings

The second one might be preferable since it fixes the issue for any similar plugins. I don't have enough familiarity into vim scripting and the vimfiler code to come up with a good way to accomplish that, though (I assume disabling it entirely wouldn't be to your liking).

I will shortly submit a pull request which implements the first one (disabling it for all Windows versions of vim), since this does at least allow things to work.
