### ISSUE TITLE
Cannot open files through vimfiler/Unite when using neossh.vim

### ISSUE THREAD

**Issue by mikn** [Shougo/neossh.vim#14]
Hi,
I've been trying for a while now to open files using VimFiler/Unite together with neossh, but I don't seem to be doing it right. It tries to open a path that looks like this: `ssh://hostname:/path/to/file` while the native scp implementation in Vim seems to expect it in the format of: `scp://hostname/path/to/file` (notice `scp` and lack of `:`).
Browsing the server seems to work very well, though, so it is only really preview/edit/open that does not work.
Looking at the code for open here: https://github.com/Shougo/neossh.vim/blob/master/autoload/unite/kinds/file_ssh.vim#L64
it seems to expect vim to handle this natively (?)
So, what's going wrong? :) I've tried both with vim 2:7.4.963-1+b1 (debian) and with the latest neovim compiled yesterday from master and no difference.

**Comment by Shougo** [comment]
Fixed.
You should specify it by vimfiler instead `:edit`.

```vim
:VimFiler ssh://hostname/path
```
