### ISSUE TITLE
neossh fails if .ssh/config is missing

### ISSUE THREAD

**Issue by imain** [Shougo/neossh.vim#17]
I don't have a .ssh/config normally.  Don't really need one.  I just use ssh-agent to add my keys and can log in to remote systems with no problem.  I had to trace neossh to find that it was failing trying to find a .ssh/config.  I just did 'touch .ssh/config' and it worked.  I think this is probably a bug?

**Comment by imain** [comment]
Well, if a .ssh/config is required, even an error message would be nice.  It just silently failed.

**Comment by Shougo** [comment]
The directory is required.
I have added the error message.
